### ISSUE TITLE
维度不匹配

### ISSUE THREAD

**Issue by leizeling** [yijiuzai/chinese-ocr#2]
运行时出现如下错误，请问有什么解决办法吗？
Traceback (most recent call last):
  File "/home/ustc/Desktop/chinese-ocr-master/demo.py", line 2, in <module>
    import model
  File "/home/ustc/Desktop/chinese-ocr-master/model.py", line 6, in <module>
    from crnn.crnn import crnnOcr
  File "/home/ustc/Desktop/chinese-ocr-master/crnn/crnn.py", line 47, in <module>
    model,converter = crnnSource()
  File "/home/ustc/Desktop/chinese-ocr-master/crnn/crnn.py", line 43, in crnnSource
    model.load_state_dict(torch.load(path))
  File "/home/ustc/anaconda3/envs/chinese_ocr_master/lib/python3.5/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for CRNN:
	While copying the parameter named "rnn.1.embedding.weight", whose dimensions in the model are torch.Size([5531, 512]) and whose dimensions in the checkpoint are torch.Size([5530, 512]).
	While copying the parameter named "rnn.1.embedding.bias", whose dimensions in the model are torch.Size([5531]) and whose dimensions in the checkpoint are torch.Size([5530]).

**Comment by RayJueZhu** [comment]
可以提供下之前的vgg的模型吗，或者是怎么训练的阿？
